### ISSUE TITLE
M1 Chip Conda Environment Issues

### ISSUE THREAD

**Issue by roseisgold** [McGranahanLab/CONIPHER-wrapper#2]
Hi! I am trying to install CONIPHER but am running into issues due to the Mac M1 chip--the conda environment is unable to install r-seqminer and r-base=3.6.1 . Any suggestions on how to circumvent this issue? Thank you!

**Comment by itigupta2429** [comment]
Hii,
Any possible solution/s to this? 
I am facing the same issue and have tried on multiple systems/environments.

**Comment by arihueb** [comment]
Hi, sorry for the late response. After updating the package and conda environment (CONIPHER version 2.2.0) this should now work for M1 chips as well.
